### ISSUE TITLE
Password column length in oauth_users

### ISSUE THREAD

**Issue by ybelenko** [dsquier/oauth2-server-php-mysql#10]
PHP [`password_hash`](https://www.php.net/manual/en/function.password-hash.php) function doc says:

> **`PASSWORD_DEFAULT`** - Use the bcrypt algorithm (default as of PHP 5.5.0). Note that this constant is designed to change over time as new and stronger algorithms are added to PHP. For that reason, the length of the result from using this identifier can change over time. Therefore, it is recommended to store the result in a database column that can expand beyond 60 characters (255 characters would be a good choice).

I think it's a good point to increase column length:
https://github.com/dsquier/oauth2-server-php-mysql/blob/266c239afc987ad890c8456239489f6bf2573e08/oauth.ddl#L95
```diff
---   password            VARCHAR(80),
+++   password            VARCHAR(255),
```

**Comment by dsquier** [comment]
Agreed, Submit a PR and I'll merge.
