### ISSUE TITLE
OAUTH_USERS.USER_ID is missing

### ISSUE THREAD

**Issue by ybelenko** [dsquier/oauth2-server-php-mysql#11]
Can't understand where is `user_id` column in following table:

https://github.com/dsquier/oauth2-server-php-mysql/blob/266c239afc987ad890c8456239489f6bf2573e08/oauth.ddl#L93-L101

**Comment by dsquier** [comment]
I do not believe `user_id` is part of the OAuth spec, which is why it is not included. If this is part of the library, I can see reason to include it. If you can point to this in the code, I'm happy to take a PR.

**Comment by ybelenko** [comment]
@dsquier Wow. I'm so lucky to finally meet you here. We looked for other packages because cannot reach you. Can you say what this repo's license?

**Comment by ybelenko** [comment]
We discuss integration of your schema into openapi-generator project in https://github.com/OpenAPITools/openapi-generator/pull/5807

**Comment by ybelenko** [comment]
I've spent some time checking implementations. This [User ID | OAuth2 Server PHP](https://bshaffer.github.io/oauth2-server-php-docs/overview/userid/) link says that `user_id` is optional parameter, so `oauth_access_tokens.user_id != oauth_users.username`.

However following implementation says:
https://github.com/bshaffer/oauth2-server-php/blob/c0c5f2c9ee1e676920062653b2d7b9e9095cd860/src/OAuth2/Storage/Pdo.php#L456-L459

I think issue can be closed, because I didn't find any doc to prove my point.
